<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;net10.0-windows</TargetFrameworks>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
	<Version>1.2.3-beta4</Version>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
	<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

	
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\AutoUpdater.NET\AutoUpdater.NET.csproj" />
    <ProjectReference Include="..\ZipExtractor\ZipExtractor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>