<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <RootNamespace>AutoUpdaterTestWPF</RootNamespace>
    <AssemblyName>AutoUpdaterTestWPF</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoUpdater.NET\AutoUpdater.NET.csproj" />
  </ItemGroup>
</Project>